---
title: "Untitled"
author: "Matthew Aaron Looney"
date: "12/14/2017"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

```{r setup, include=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(readr)
library(dplyr)
library(readxl)
library(maps)
library(feather)
library(stringr)

# library(zipcode)
# library(xlsx)
# library(ggmap)

```

```{r load data, cache=TRUE, include=FALSE, message=FALSE, warning=FALSE, echo=FALSE}

################################################################################
# beer_drug_1583_1634 <- read.csv("~/Documents/IRI_Original_Data/Year 10 and 11 DVD/Year10/beer/beer_drug_1583_1634", sep="")
# 
# beer_groc_1583_1634 <- read.csv("/Users/malooney/Documents/IRI_Original_Data/Year 10 and 11 DVD/Year10/beer/beer_groc_1583_1634", sep="")
#    
# Delivery_Stores <- read_table("/Users/malooney/Documents/IRI_Original_Data/Year 10 and 11 DVD/Year10/beer/Delivery_Stores")
# 
# IRI_week_translation_2008_2017 <- read_excel("/Users/malooney/Documents/IRI_Original_Data/Year 10 and 11 DVD/Year10/beer/IRI week translation_2008_2017.xls", col_types = c("numeric", "date", "date", "skip", "skip", "skip"))
# 
# beer_prod_attr_2011_edit <- read_table("/Users/malooney/Google Drive/digitalLibrary/*MS_Thesis/MS_Thesis/data/beer_prod_attr_2011_edit")
# 
# prod11_beer <- read_excel("~/Documents/IRI_Original_Data/Year 8 and 9 DVD/parsed stub files 2008-2011/prod11_beer.xlsx")

################################################################################

#write_feather(beer_drug_1583_1634, "/Users/malooney/Google Drive/digitalLibrary/*MS_Thesis/MS_Thesis/data/beer_drug_1583_1634_feather")

beer_drug_1583_1634 <- read_feather("/Users/malooney/Google Drive/digitalLibrary/*MS_Thesis/MS_Thesis/data/beer_drug_1583_1634_feather")

#write_feather(beer_groc_1583_1634, "/Users/malooney/Google Drive/digitalLibrary/*MS_Thesis/MS_Thesis/data/beer_groc_1583_1634_feather")

beer_groc_1583_1634 <- read_feather("/Users/malooney/Google Drive/digitalLibrary/*MS_Thesis/MS_Thesis/data/beer_groc_1583_1634_feather")

#write_feather(Delivery_Stores, "/Users/malooney/Google Drive/digitalLibrary/*MS_Thesis/MS_Thesis/data/Delivery_Stores_feather")

Delivery_Stores <- read_feather("/Users/malooney/Google Drive/digitalLibrary/*MS_Thesis/MS_Thesis/data/Delivery_Stores_feather")

#write_feather(IRI_week_translation_2008_2017, "/Users/malooney/Google Drive/digitalLibrary/*MS_Thesis/MS_Thesis/data/IRI_week_translation_2008_2017_feather")

IRI_week_translation_2008_2017 <- read_feather("/Users/malooney/Google Drive/digitalLibrary/*MS_Thesis/MS_Thesis/data/IRI_week_translation_2008_2017_feather")

#write_feather(beer_prod_attr_2011_edit, "/Users/malooney/Google Drive/digitalLibrary/*MS_Thesis/MS_Thesis/data/beer_prod_attr_2011_edit_feather")

beer_prod_attr_2011_edit <- read_feather("/Users/malooney/Google Drive/digitalLibrary/*MS_Thesis/MS_Thesis/data/beer_prod_attr_2011_edit_feather")

#write_feather(prod11_beer, "/Users/malooney/Google Drive/digitalLibrary/*MS_Thesis/MS_Thesis/data/prod11_beer_feather")

prod11_beer <- read_feather("/Users/malooney/Google Drive/digitalLibrary/*MS_Thesis/MS_Thesis/data/prod11_beer_feather")

################################################################################

#data(county.fips)
#View(county.fips)

```

```{r manipulate data, cache=TRUE, include=FALSE, message=FALSE, warning=FALSE, echo=FALSE}

################################################################################
# join grocery store and drug store data
main_beer_drug_and_groc <- rbind(beer_drug_1583_1634, beer_groc_1583_1634)
################################################################################

################################################################################
## make UPC for main_beer_drug_and_groc
upc_fun <- function(x){

  paste(
    str_pad(x[1], 2, "left", pad="0"),
    str_pad(x[2], 2, "left", pad="0"),
    str_pad(x[3], 5, "left", pad="0"),
    str_pad(x[4], 5, "left", pad="0"), sep="-")
  }

temp <- main_beer_drug_and_groc[, 3:6]

temp_main <- data.frame(upc=apply(temp, MARGIN = 1, upc_fun))

main_beer_drug_and_groc <- cbind(main_beer_drug_and_groc, temp_main)

write_feather(main_beer_drug_and_groc, "/Users/malooney/Google Drive/digitalLibrary/*MS_Thesis/MS_Thesis/data/main_beer_drug_and_groc_feather")

main_beer_drug_and_groc <- read_feather("/Users/malooney/Google Drive/digitalLibrary/*MS_Thesis/MS_Thesis/data/main_beer_drug_and_groc_feather")
################################################################################

################################################################################
## join week codes, (IRI_week...) with main_beer_drug_and_groc file.
main_beer_drug_and_groc_1 <- left_join(x=main_beer_drug_and_groc, y=IRI_week_translation_2008_2017, by=c("WEEK" = "IRI Week"))

write_feather(main_beer_drug_and_groc_1, "/Users/malooney/Google Drive/digitalLibrary/*MS_Thesis/MS_Thesis/data/main_beer_drug_and_groc_1_feather")

main_beer_drug_and_groc_1 <- read_feather("/Users/malooney/Google Drive/digitalLibrary/*MS_Thesis/MS_Thesis/data/main_beer_drug_and_groc_1_feather")
################################################################################

################################################################################
## make UPC for beer_prod_attr_2011_edit
upc_fun <- function(x){

  paste(
    str_pad(x[1], 2, "left", pad="0"),
    str_pad(x[2], 2, "left", pad="0"),
    str_pad(x[3], 5, "left", pad="0"),
    str_pad(x[4], 5, "left", pad="0"), sep="-")
  }

temp <- beer_prod_attr_2011_edit[, 1:4]

temp_main <- data.frame(upc=apply(temp, MARGIN = 1, upc_fun))

beer_prod_attr_2011_edit <- cbind(beer_prod_attr_2011_edit, temp_main)

################################################################################

################################################################################
# join main_beer_drug_and_groc_2 to prod11_beer
main_beer_drug_and_groc_2 <- left_join(y=prod11_beer, x=main_beer_drug_and_groc_2, by=c("upc" = "UPC"))


################################################################################

################################################################################
# join Delivery_Stores to main_beer_drug_and_groc
main_beer_drug_and_groc_2 <- left_join(x=main_beer_drug_and_groc_1, y=Delivery_Stores, by="IRI_KEY")

write_feather(main_beer_drug_and_groc_2, "/Users/malooney/Google Drive/digitalLibrary/*MS_Thesis/MS_Thesis/data/main_beer_drug_and_groc_2_feather")

main_beer_drug_and_groc_2 <- read_feather("/Users/malooney/Google Drive/digitalLibrary/*MS_Thesis/MS_Thesis/data/main_beer_drug_and_groc_2_feather")
################################################################################













```















```{r map, eval=FALSE, include=FALSE, message=FALSE, warning=FALSE, cache=TRUE, results='asis'}
################################################################################
   
urlfile <-'http://www.psc.isr.umich.edu/dis/census/Features/tract2zip/MedianZIP-3.xlsx'
destfile <- "census20062010.xlsx"
download.file(urlfile, destfile, mode="wb")

census <- xlsx::read.xlsx2(destfile, sheetName = "Median")
   
census <- census[c('Zip','Median..')]
names(census) <- c('Zip','Median')
census$Median <- as.character(census$Median)
census$Median <- as.numeric(gsub(',','',census$Median))
#print(head(census,5))
   
data(zipcode)
census$Zip <- clean.zipcodes(census$Zip)
   
census <- merge(census, zipcode, by.x='Zip', by.y='zip')
   
map <-get_map(location="united states", zoom= 4,
             maptype = "roadmap", source='google',color='color')
   
ggmap(map) + geom_point(
  aes(x=longitude, y=latitude, colour=Median), 
  data=census, alpha=.05, na.rm = T)  + 
  scale_color_gradient(low="beige", high="blue")
   
################################################################################
```

