---
title: "Untitled"
author: "Matthew Aaron Looney"
date: "12/14/2017"
output: pdf_document
---

```{r setup, include=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(readr)
library(dplyr)
library(readxl)
library(stringr)

```


```{r echo=FALSE, warning=FALSE, message=FALSE}

beer_PANEL_GK_1635_1686 <- read_csv("~/Documents/IRI_Original_Data/Year 10 and 11 DVD/Year11/External/beer/beer_PANEL_GK_1635_1686.DAT")

beer_PANEL_DK_1635_1686 <- read_csv("~/Documents/IRI_Original_Data/Year 10 and 11 DVD/Year11/External/beer/beer_PANEL_DK_1635_1686.DAT")

beer_PANEL_MK_1635_1686 <- read_csv("~/Documents/IRI_Original_Data/Year 10 and 11 DVD/Year11/External/beer/beer_PANEL_MK_1635_1686.DAT")

DEMOS <- read_csv("~/Documents/IRI_Original_Data/Year 10 and 11 DVD/Year11/External/beer/DEMOS.CSV")

IRI_week_translation_2008_2017 <- read_excel("~/Documents/IRI_Original_Data/Year 10 and 11 DVD/Year11/External/beer/IRI week translation_2008_2017.xls", 
     col_types = c("numeric", "date", "date", 
         "skip", "skip", "skip"))

Delivery_Stores <- read_table("~/Documents/IRI_Original_Data/Year 10 and 11 DVD/Year11/External/beer/Delivery_Stores")

beer_prod_attr_edit <- read_table("/Users/malooney/Google Drive/digitalLibrary/*MS_Thesis/MS_Thesis/data/beer_prod_attr_edit")

## create COLUPC for merge of beer_prod_attr_edit with main data frame
i <-1
temp <- list()
temp_main <- data.frame(colCPU=1:length(beer_prod_attr_edit$SY))

for(i in 1:length(temp_main$colCPU)){
  
temp$SY <- str_pad(beer_prod_attr_edit[i,1], 2, "left", pad="0")
temp$GE <- str_pad(beer_prod_attr_edit[i,2], 1, "left", pad="0")
temp$VEND <- str_pad(beer_prod_attr_edit[i,3], 5, "left", pad="0")
temp$ITEM <- str_pad(beer_prod_attr_edit[i,4], 5, "left", pad="0")

temp$main <- paste(temp$SY, temp$GE, temp$VEND, temp$ITEM, sep="")

temp_main[i,1] <- temp$main

i <- i+1

}

beer_prod_attr_edit <- cbind(beer_prod_attr_edit, temp_main)

main_data_GK_DK_MK <- rbind(beer_PANEL_GK_1635_1686, beer_PANEL_DK_1635_1686, beer_PANEL_MK_1635_1686)

merge_main_data_GK_DK_MK_Demos <- left_join(y=DEMOS, x=main_data_GK_DK_MK, by=c("PANID" = "Panelist ID"))

merge_main_data_GK_DK_MK_Demos$`Combined Pre-Tax Income of HH` <- as.numeric(merge_main_data_GK_DK_MK_Demos$`Combined Pre-Tax Income of HH`) 

merge_main_data_GK_DK_MK_Demos_Date <- left_join(y=IRI_week_translation_2008_2017, x=merge_main_data_GK_DK_MK_Demos, by=c("WEEK" = "IRI Week"))

merge_main_data_GK_DK_MK_Demos_Date_Store <- left_join(y=Delivery_Stores, x=merge_main_data_GK_DK_MK_Demos_Date, by=c("IRI_KEY" = "IRI_KEY"))

merge_main_data_GK_DK_MK_Demos_Date_Store_Prod_Attr <- left_join(y=beer_prod_attr_edit, x=merge_main_data_GK_DK_MK_Demos_Date_Store, by=c("COLUPC" = "colCPU"))

write.csv(merge_main_data_GK_DK_MK_Demos_Date_Store_Prod_Attr, file = "/Users/malooney/Google Drive/digitalLibrary/*MS_Thesis/MS_Thesis/data/merge_main_data_GK_DK_MK_Demos_Date_Store_Prod_Attr.csv", row.names = FALSE)



```











