---
title: "Does Ethnicity Influence Beer Consumption and Brand Choice?"
subtitle: ""
author: "Matthew Aaron Looney"
date: "February 15, 2018"

output:
  pdf_document:
    fig_caption: yes
    number_sections: yes
    toc: no
    toc_depth: 4
  html_document:
    toc: yes
    toc_depth: '4'
    
abstract: "The beer industry in the United States represents more than $350 billion dollars of total economic impact. This makes the industry one of the largest consumer product sectors in America. As a category of consumer goods, beer is one of the most dynamically changing products in the country. The industry responds quickly to changes in consumer preference and shifting consumer demographics. The continued ability to understand and predict shifting consumer demand is paramount to the industries' ability to continue to innovate and selectively appeal to the heterogeneous consumer. It is well known that consumer demographics play a key role in determining consumer preference. A recent study by Lopez and Matschke [-@Lopez:2012ei] examine consumer preference for beer using market level data. The authors assume a heterogeneous agent model with age and income variation across consumers. Consistent with expectations, they find a strong relationship between increased age and income and lower sensitivity to price. However, the study omits other relevant consumer demographic variables, such as ethnicity. This study seeks to understand more deeply how additional consumer characteristics influence preference for beer; and in particular, how ethnicity influences beer consumption and brand choice. The methodological approach taken in this study is to estimate a differentiated demand for beer using a random coefficients discrete choice model. Information Resources, Inc. (IRI) brand level data will be used as well as consumer level demographic data from the Current Population Survey (CPS).
"
    
header-includes:
- \usepackage{graphicx}
- \usepackage{rotating}
- \usepackage{longtable}
- \usepackage{amssymb,amsmath}
- \usepackage{dcolumn}
- \usepackage{setspace}
- \usepackage{mathrsfs}
- \usepackage{eso-pic,graphicx,transparent}

bibliography: differentiated_Beer_Demand.bib
csl: computational-economics.csl
link-citations: true
fontsize: 12pt
geometry: margin = 1.25in

---

<!-- \AddToShipoutPictureFG{ -->
<!--   \AtPageCenter{% or \AtTextCenter -->
<!--     \makebox[0pt]{\rotatebox[origin=c]{45}{% -->
<!--       \scalebox{5}{\texttransparent{0.05}{DRAFT}}% -->
<!--     }} -->
<!--   } -->
<!-- } -->

\newpage

# Introduction

\doublespacing

\qquad According to a study by the Pew Research Center, by the year 2055 the United States will no longer have a single racial or ethnic majority [@cohn201610]. In 1965, 84% of Americans were non-Hispanic Whites, 11% Black, 4% Hispanic, less than 1% Asian and less than 1% other. By the year 2015 the ethnic distribution of the United States had shifted with non-Hispanic whites now representing 62% of the U.S. population, 12% Black, 18% Hispanic, 6% Asian and 2% other.^[Whites, Blacks and Asians include only single-race non-Hispanics. Asians include Pacific Islanders. Hispanics are of any race. Source: Pew research Center estimates based on adjusted census data] Over a 50 year period the American demographic landscape had changed with large increases in Hispanic and Asian representation. These divergent trends are expected to continue long into the future at variable rates depending on how immigration policy morphs with fluctuations in the political landscape [@passel2015modern].
  
  
\qquad When discussing ethnic trends it has become important to distinguish ethnicity from race and to define these terms precisely. Unfortunately this is not a trivial task. The classic definitions of race and ethnicity used by sociologists and anthropologist are given by the following two definitions. Race refers to a category of people who share certain inherited physical characteristics, such as skin color, facial features, and stature. Using physical differences as their criteria, scientists at one point identified as many as nine races [@Smedley:1998wf].^[African, American Indian or Native American, Asian, Australian Aborigine, European (more commonly called “white”), Indian, Melanesian, Micronesian, and Polynesian] Ethnicity refers to the shared social, cultural, and historical experiences, stemming from common national or regional backgrounds, that make subgroups of a population different from one another. Within the context of ethnicity, an ethnic group can be defined as a subgroup of a population with a set of shared social, cultural, and historical experiences; with relatively distinctive beliefs, values, and behaviors; and with some sense of identity of belonging to the subgroup [@Barkan:2016wf].  
  
  
\qquad There has been much debate and disagreement within the social science community when dealing with issues of race and ethnicity. However, the current general consensus is that biological definitions of race are antiquated and largely irrelevant. Issues of racial classification based on genetic profiling have muddied the waters even further.^[With the availability of DNA testing by companies such as Ancestry.com and 23andMe many people discover the true racial diversity within their genes.] With the current level of genetic diversity present in the world today it is not possible to classify an individual as purely one race over another. The idea of racial classification based on biology has dissolved and the idea of ethnic identity has emerged as the preferred method of individual demographic identifier. Due to the complexity of the problems related to using biological race as a demographic identifier we will instead use the concept of ethnicity as defined above. An increasing number of data sets are including questions about ethnicity. This self reporting of ethnic identity is fundamentally inline with the widely accepted definitions of ethnicity and thus we feel it more appropriate to use ethnic demographic information when studying consumer preference.  
  
  
\qquad Distinct patterns of immigration from Latin America and Asia is driving much of the current change in the demographic landscape. Hispanics and Asians are estimated to represent 70% of the total immigrant population by the year 2055 with 34% and 36%, respectively [@cohn201610]. But immigration patterns represent more than simple statistics. Immigrants are people who bring with them ethnic identity and culture. This ethnic identity is embedded in food, religion, language, and to varying degrees, permeates every aspect of an individuals identity.  The United States has always been a nation of immigrants. Since it's founding, the country has undergone three distinct episodes of immigration. The most recent between 1850 to 1930 when large waves of immigrants from Germany, Italy, Ireland, Greece and many eastern European nations landed on American soil. These immigrants changed the American food scene by bringing their food preferences with them from their home countries. Given the current changes in the ethnic landscape of the United States, it is widely accepted that a fourth episode of immigration is underway. Consumer food preference last generation is looking very different from consumer food preference in the current generation. In fact, at the current pace of ethnic change, shifts in inter-generational food preference are becoming a reality that the U.S. food industry will need to manage to appeal to the heterogeneous consumer. Understanding how food preferences change with large populations from Latin America and Asia settling in the fabric of the United States is an important research question for economist to tackle. Many studies incorporate consumer income and age variations when studying demand for differentiated goods but few explicitly model ethnicity as an added demographic variable. We argue that ethnicity is an important component to consider when studying consumer demand. This study seeks to understand more deeply how additional consumer characteristics influence product preference, and in particular, how ethnicity influences beer consumption and brand choice. 
  
  
\qquad One of the largest consumer product sectors in America is the beer industry. As a whole, this industry represents more than $350 billion dollars of total economic impact ^[Based on data from 2016 in a study by John Dunham & Associates.]. As a category of consumer goods, beer is one of the most dynamically changing products in the country. The industry responds quickly to changes in consumer preference and shifting consumer demographics. The ability of the beer industry to change quickly to appeal to a new consumer group makes the industry an interesting candidate to study with regard to changing ethnic diversity.  
  
  
## Literature Review  
  
  
\qquad The theoretical framework for projecting consumer choice onto a set of product characteristics originated with work by Kelvin Lancaster [-@Lancaster:1966tp]. This idea was extended further and the econometric model was developed by Daniel McFadden [-@mcfadden1973conditional]. This projection allowed for the estimation of a large number of products using a finite number of characteristics. Prior to this line of research the problem of dimensionality plagued empirical industrial organization and rendered many interesting problems intractable.
  
  
\qquad While dimensionality was a large problem to overcome, price endogeneity is present is almost all supply and demand models and discrete choice modeling is no exception. If we fail to account for this endogeneity then our parameter estimates will be biased and inconsistent. Berry's 1994 Rand paper provides a method to overcome the endogeneity issue [-@Berry:1994tp]. He provides a method to estimate differentiated demand models in the presence of unobserved product characteristics by inverting the market share equation to obtain an estimate of mean utility. Once the implied mean utility is obtained the estimation can proceed in a similar way as homogeneous goods modeling. While Berry's method allows for the handling of endogenous prices through the use of standard linear instrumental variables his method does not address the well known problem of independence of irrelevant alternatives (iia).  
  
  
\qquad The incorporation of consumer heterogeneity in discrete choice modeling of differentiated products explicitly address the iia issue. In a 1995 Econometrica paper by Steven Berry, James Levinsohn and Ariel Pakes (BLP) [-@Berry:1995ud] it was shown that individual consumer heterogeneity can be applied to a discrete choice model of differentiated goods in a tractable way to uncover consistent estimations of demand elasticities. The BLP model developed a way to break the iia property which allowed for more realistic substitution patterns across products. The BLP model has become a popular model in industrial organization and has become the model of choice when investigating merger simulations.  
  
  
\qquad It is well known that consumer demographics play a key role in determining consumer preference. A search of the literature related to discrete choice modeling of differentiated goods reveal few studies that incorporate other demographic variables beyond income and age. A study by Lopez and Matschke [-@Lopez:2012ei] examine consumer preference for beer using market level data. The authors assume a heterogeneous agent model with age and income variation across consumers. Consistent with expectations, they find a strong relationship between increased age and income and lower sensitivity to price. However, the authors omit other relevant consumer demographic variables, such as ethnicity. One of the few studies to incorporate an ethnic variable in a random coefficients discrete choice model was performed by Charles Romeo [@Romeo:2016wx]. His results show that as the percentage of Hispanics in the population increase, the utility gained from consuming Corona decrease and turn negative with 18 to 22 percent Hispanics. Romeo can not offer any clear explanation of these results but suggests that perhaps with increasing percentages of Hispanics in the market, competition from other Latin American beers are moving consumers away from Corona. 
  
  
## Conceptual Framework



## Methodology
  
  
\qquad The methodological approach taken in this study is to estimate a differentiated demand for beer using a random coefficients discrete choice model. IRI Brand level data will be used as well as consumer level demographic data from the Current Population Survey.  
  

















\newpage

\singlespace

# Notes:
## Not included in paper

Include information about the beer industries ability to shift focus quickly to appeal to changes in age demographics, ie. Millennial, with the development of the craft beer industry; reference PhD thesis work by Toro and subsequent work that stemmed from his thesis.

need to get more clear about how to use a counter-factual to demonstrate and disentangle the demand shift. Is it beer industry responding to changing ethnic diversity that is causing ethnic groups to change their choice preference (marketing targeted to ethnic groups) or is it changing ethnic diversity that is causing the beer industry to change their products to meet a changing demographic variable. Or does it matter This does not need to be in the introduction but needs to be addressed at some point, maybe

Expand the methodology used with some generic formulation of BLP theory; just enough to give the reader an idea of how I am going to preform the study and what information will be obtained, ie elasticities, etc. Will save the in depth formulation for the theory section. Also need to explain the market and brand choice definitions quickly. Again I will save the in depth descriptions for the data and methodology sections


\newpage

# References

